### ISSUE TITLE
Clearfix Compatibility

### ISSUE THREAD

**Issue by kmctown** [styled-components/polished#140]
This is a great library and I'm using it with `styled-components`, but having an issue `clearFix` interoping with bootstrap. The `clearFix` implementation is slightly different than bootstrap's and it doesn't seem to work with the Grid.

E.g., the `polished` implementation:

```css
&:after {
  clear: both;
  content: '';
  display: table;
}
```

vs. the Bootstrap implementation:

```css
&:before,
&:after {
  clear: both;
  display: table;
  content: "";
  line-height: 0;
}
```

Would be more than happy to submit a PR for this if you all are open to the change. Thanks!
