### ISSUE TITLE
Keyframes animation needed.

### ISSUE THREAD

**Issue by zhaojinxiang** [styled-components/polished#249]
I want write:
``` css
.App-logo {
  animation: App-logo-spin infinite 20s linear;
  height: 80px;
}

@keyframes App-logo-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
```

So I wrote such js code:

```javascript
const keyframesStyle =  WhatShouldIWriteHere?

const appLogo = {
  // animation: 'App-logo-spin infinite 20s linear',
  ...animation([keyframesStyle, 'infinite', '20s', 'linear']),
  height: '80px',
};
```

Is there any Keyframes animation function in polished?

------------------------------------------------

My now solution is import 'foo.style.css';
```css
@keyframes App-logo-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
```
and 
```javascript
import 'foo.style.css';
const keyframesStyle = 'App-logo-spin';
```
